### ISSUE TITLE
The new version cannot be used

### ISSUE THREAD

**Issue by biner88** [beanjs-kicad/beantools#2]
```
Traceback (most recent call last):
  File "C:\Users/Administrator/Documents/KiCad/5.99/scripting\plugins\beantools\beantools\teardrops\dialog.py", line 143, in onProcessAction
    count = SetTeardrops(self.sp_hpercent.GetValue(),
  File "C:\Users/Administrator/Documents/KiCad/5.99/scripting\plugins\beantools\beantools\teardrops\td.py", line 307, in SetTeardrops
    vias = __GetAllVias(pcb)[0] + __GetAllPads(pcb, pad_types)[0]
  File "C:\Users/Administrator/Documents/KiCad/5.99/scripting\plugins\beantools\beantools\teardrops\td.py", line 48, in __GetAllPads
    for i in range(board.GetPadCount()):
AttributeError: 'BOARD' object has no attribute 'GetPadCount'
Traceback (most recent call last):
  File "C:\Users/Administrator/Documents/KiCad/5.99/scripting\plugins\beantools\beantools\teardrops\dialog.py", line 143, in onProcessAction
    count = SetTeardrops(self.sp_hpercent.GetValue(),
  File "C:\Users/Administrator/Documents/KiCad/5.99/scripting\plugins\beantools\beantools\teardrops\td.py", line 307, in SetTeardrops
    vias = __GetAllVias(pcb)[0] + __GetAllPads(pcb, pad_types)[0]
  File "C:\Users/Administrator/Documents/KiCad/5.99/scripting\plugins\beantools\beantools\teardrops\td.py", line 48, in __GetAllPads
    for i in range(board.GetPadCount()):
AttributeError: 'BOARD' object has no attribute 'GetPadCount'
Traceback (most recent call last):
  File "C:\Users/Administrator/Documents/KiCad/5.99/scripting\plugins\beantools\beantools\teardrops\dialog.py", line 143, in onProcessAction
    count = SetTeardrops(self.sp_hpercent.GetValue(),
  File "C:\Users/Administrator/Documents/KiCad/5.99/scripting\plugins\beantools\beantools\teardrops\td.py", line 307, in SetTeardrops
    vias = __GetAllVias(pcb)[0] + __GetAllPads(pcb, pad_types)[0]
  File "C:\Users/Administrator/Documents/KiCad/5.99/scripting\plugins\beantools\beantools\teardrops\td.py", line 48, in __GetAllPads
    for i in range(board.GetPadCount()):
AttributeError: 'BOARD' object has no attribute 'GetPadCount'

```

**Comment by easyw** [comment]
this can be solved changing:
https://github.com/beanjs-kicad/beantools/blob/3fa82ba92ba97d7aac80ee6898f3168596498a56/beantools/teardrops/td.py#L48
to:
`    for i in range(len(board.GetPads())):`

**Comment by biner88** [comment]
Already solved my problem, thank you@easyw
